buildscript {
    dependencies {
        classpath libs.jdbc.postgres
        classpath libs.flyway.postgres
    }
}

plugins {
    id 'java'
    alias(libs.plugins.flyway)
    alias(libs.plugins.jooq)
    id 'common-java'
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation project(':notification')
    implementation project(':scheduling')

    implementation libs.argon2
    implementation libs.amazon.s3
    implementation libs.vertx.auth.jwt
    implementation libs.vertx.web
    implementation libs.bundles.jjwt

    testImplementation libs.local.s3.rest
    testImplementation libs.local.s3.jupiter

    testCompileOnly libs.simple.mail
}

processResources {
    filesMatching("application.yaml") {
        expand([
                auth_secret : System.getenv('AUTH_JWT_SECRET'),
                reset_secret: System.getenv('RESET_JWT_SECRET')
        ])
    }
}