/*
 * Provve API
 * Операции, требующие идентификатор аккаунта, извлекают идентификатор из токена авторизации.
 *
 * The version of the OpenAPI document: beta
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.provve.api.client;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class Pair {

    private final String name;

    private final String value;

    public Pair(String name, String value) {
        this.name = isValidString(name) ? name : "";
        this.value = isValidString(value) ? value : "";
    }

    private static boolean isValidString(String arg) {
        return arg != null;
    }

    public String getName() {
        return this.name;
    }

    public String getValue() {
        return this.value;
    }
}
