buildscript {
    dependencies {
        classpath libs.jdbc.postgres
        classpath libs.flyway.postgres
    }
}

plugins {
    alias(libs.plugins.flyway)
    alias(libs.plugins.jooq)
    id 'common-java'
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation project(':accounts')
    implementation libs.bundles.jjwt
    implementation libs.failsafe

    testImplementation project(':notification')
}

processResources {
    filesMatching("application.yaml") {
        expand([
                merchant_login : System.getenv('ROBOKASSA_LOGIN'),
                shop_password_1: System.getenv('ROBOKASSA_PASSWORD_1')
        ])
    }
}