# --- Console Writer ---
writer1=console
writer1.format=[{date: HH:mm:ss}] {level}: {message}
writer1.level=info
# --- Rolling File Writer ---
writer2=rolling file
writer2.file=logs/{date}-{count}.log
writer2.policies=daily: 00:00@UTC
writer2.charset=UTF-8
writer2.backups=100
# --- Logger Levels ---
level@io.vertx.ext.web=info
# --- General Settings ---
writingthread=true
