openapi: "3.1.0"
info:
  title: Antifraud API
  version: "beta"
servers:
  - url: http://localhost

paths:
  /mac:
    get:
      summary: Получить MAC
      responses:
        '200':
          description: MAC отправлен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mac"


  /observation:
    get:
      summary: Получить результат наблюдения
      responses:
        '200':
          description: Наблюдение отправлено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Observation"

  /echo:
    get:
      summary: Проверить присутствие
      responses:
        '200':
          description: Антифрод установлен

components:
  schemas:
    Mac:
      type: object
      properties:
        mac:
          type: string
          description: MAC Антифрода для подтверждения подлинности.
    Observation:
      allOf:
        - $ref: "#/components/schemas/Mac"
        - type: object
          properties:
            violations:
              type: array
              items:
                enum:
                  - remote_control # к пк экзаминуемого подключались по протоколам удалённого рабочего стола
                  - clipboard # замечено вставка решения из буфера обмена
                  - web # замечено испльзование интернет-ресурсов для поиска ответов
              description: Какие запрещённые действия пользователь совершал. Если указано, значит совершал.