buildscript {
    dependencies {
        classpath libs.jdbc.postgres
        classpath libs.flyway.postgres
    }
}

plugins {
    id 'java'
    alias(libs.plugins.flyway)
    alias(libs.plugins.jooq)
    id 'common-java'
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation libs.simple.mail

    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor

    testImplementation libs.testcontainers.mailpit
}

processResources {
    filesMatching("application.yaml") {
        expand([
                mail_password: System.getenv('MAIL_PASSWORD')
        ])
    }
}