package tech.provve.statemachine.service;

import java.security.SecureRandom;

public class SecretGenerator {

    /**
     * Generates a random secret as a byte array.
     *
     * @param numBytes Number of bytes to generate.
     * @return A randomly-generated byte array.
     */
    public static byte[] generateSecret(int numBytes) {
        SecureRandom secureRandom = new SecureRandom();
        byte[] secretBytes = new byte[numBytes];
        secureRandom.nextBytes(secretBytes);
        return secretBytes;
    }

    /**
     * Converts a byte array to its hexadecimal representation.
     *
     * @param bytes Input byte array.
     * @return Hexadecimal string representing the input byte array.
     */
    public static String bytesToHex(byte[] bytes) {
        final char[] HEX_ARRAY = "0123456789ABCDEF".toCharArray();
        char[] hexChars = new char[bytes.length * 2];
        for (int j = 0; j < bytes.length; j++) {
            int v = bytes[j] & 0xFF;
            hexChars[j * 2] = HEX_ARRAY[v >>> 4];
            hexChars[j * 2 + 1] = HEX_ARRAY[v & 0x0F];
        }
        return new String(hexChars);
    }
}