buildscript {
    dependencies {
        classpath libs.jdbc.postgres
        classpath libs.flyway.postgres
    }
}

plugins {
    id 'java'
    alias(libs.plugins.flyway)
    alias(libs.plugins.jooq)
    id 'common-java'
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation 'provve-backend:accounts'
    implementation 'provve-backend:notification'

    testImplementation libs.local.s3.rest
    testImplementation libs.local.s3.jupiter
}

jooq {
    configuration {
        generator {
            database {
                forcedTypes {
                    forcedType {
                        userType = "java.lang.Boolean"
                        binding = "tech.provve.skill.jooq_binding.BooleanBitBinding"
                        includeExpression = "reaction"
                    }
                }
            }
        }
    }
}
